# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /c/Users/User/Documents/GitHub/nethack-companion

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /c/Users/User/Documents/GitHub/nethack-companion

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /c/Users/User/Documents/GitHub/nethack-companion/CMakeFiles /c/Users/User/Documents/GitHub/nethack-companion//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /c/Users/User/Documents/GitHub/nethack-companion/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NetHack_Companion

# Build rule for target.
NetHack_Companion: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NetHack_Companion
.PHONY : NetHack_Companion

# fast build rule for target.
NetHack_Companion/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetHack_Companion.dir/build.make CMakeFiles/NetHack_Companion.dir/build
.PHONY : NetHack_Companion/fast

src/gamemap.o: src/gamemap.cpp.o
.PHONY : src/gamemap.o

# target to build an object file
src/gamemap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetHack_Companion.dir/build.make CMakeFiles/NetHack_Companion.dir/src/gamemap.cpp.o
.PHONY : src/gamemap.cpp.o

src/gamemap.i: src/gamemap.cpp.i
.PHONY : src/gamemap.i

# target to preprocess a source file
src/gamemap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetHack_Companion.dir/build.make CMakeFiles/NetHack_Companion.dir/src/gamemap.cpp.i
.PHONY : src/gamemap.cpp.i

src/gamemap.s: src/gamemap.cpp.s
.PHONY : src/gamemap.s

# target to generate assembly for a file
src/gamemap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetHack_Companion.dir/build.make CMakeFiles/NetHack_Companion.dir/src/gamemap.cpp.s
.PHONY : src/gamemap.cpp.s

src/input_handlers.o: src/input_handlers.cpp.o
.PHONY : src/input_handlers.o

# target to build an object file
src/input_handlers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetHack_Companion.dir/build.make CMakeFiles/NetHack_Companion.dir/src/input_handlers.cpp.o
.PHONY : src/input_handlers.cpp.o

src/input_handlers.i: src/input_handlers.cpp.i
.PHONY : src/input_handlers.i

# target to preprocess a source file
src/input_handlers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetHack_Companion.dir/build.make CMakeFiles/NetHack_Companion.dir/src/input_handlers.cpp.i
.PHONY : src/input_handlers.cpp.i

src/input_handlers.s: src/input_handlers.cpp.s
.PHONY : src/input_handlers.s

# target to generate assembly for a file
src/input_handlers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetHack_Companion.dir/build.make CMakeFiles/NetHack_Companion.dir/src/input_handlers.cpp.s
.PHONY : src/input_handlers.cpp.s

src/io.o: src/io.cpp.o
.PHONY : src/io.o

# target to build an object file
src/io.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetHack_Companion.dir/build.make CMakeFiles/NetHack_Companion.dir/src/io.cpp.o
.PHONY : src/io.cpp.o

src/io.i: src/io.cpp.i
.PHONY : src/io.i

# target to preprocess a source file
src/io.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetHack_Companion.dir/build.make CMakeFiles/NetHack_Companion.dir/src/io.cpp.i
.PHONY : src/io.cpp.i

src/io.s: src/io.cpp.s
.PHONY : src/io.s

# target to generate assembly for a file
src/io.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetHack_Companion.dir/build.make CMakeFiles/NetHack_Companion.dir/src/io.cpp.s
.PHONY : src/io.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetHack_Companion.dir/build.make CMakeFiles/NetHack_Companion.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetHack_Companion.dir/build.make CMakeFiles/NetHack_Companion.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetHack_Companion.dir/build.make CMakeFiles/NetHack_Companion.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/menu.o: src/menu.cpp.o
.PHONY : src/menu.o

# target to build an object file
src/menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetHack_Companion.dir/build.make CMakeFiles/NetHack_Companion.dir/src/menu.cpp.o
.PHONY : src/menu.cpp.o

src/menu.i: src/menu.cpp.i
.PHONY : src/menu.i

# target to preprocess a source file
src/menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetHack_Companion.dir/build.make CMakeFiles/NetHack_Companion.dir/src/menu.cpp.i
.PHONY : src/menu.cpp.i

src/menu.s: src/menu.cpp.s
.PHONY : src/menu.s

# target to generate assembly for a file
src/menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetHack_Companion.dir/build.make CMakeFiles/NetHack_Companion.dir/src/menu.cpp.s
.PHONY : src/menu.cpp.s

src/savefile.o: src/savefile.cpp.o
.PHONY : src/savefile.o

# target to build an object file
src/savefile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetHack_Companion.dir/build.make CMakeFiles/NetHack_Companion.dir/src/savefile.cpp.o
.PHONY : src/savefile.cpp.o

src/savefile.i: src/savefile.cpp.i
.PHONY : src/savefile.i

# target to preprocess a source file
src/savefile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetHack_Companion.dir/build.make CMakeFiles/NetHack_Companion.dir/src/savefile.cpp.i
.PHONY : src/savefile.cpp.i

src/savefile.s: src/savefile.cpp.s
.PHONY : src/savefile.s

# target to generate assembly for a file
src/savefile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetHack_Companion.dir/build.make CMakeFiles/NetHack_Companion.dir/src/savefile.cpp.s
.PHONY : src/savefile.cpp.s

src/sokoban.o: src/sokoban.cpp.o
.PHONY : src/sokoban.o

# target to build an object file
src/sokoban.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetHack_Companion.dir/build.make CMakeFiles/NetHack_Companion.dir/src/sokoban.cpp.o
.PHONY : src/sokoban.cpp.o

src/sokoban.i: src/sokoban.cpp.i
.PHONY : src/sokoban.i

# target to preprocess a source file
src/sokoban.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetHack_Companion.dir/build.make CMakeFiles/NetHack_Companion.dir/src/sokoban.cpp.i
.PHONY : src/sokoban.cpp.i

src/sokoban.s: src/sokoban.cpp.s
.PHONY : src/sokoban.s

# target to generate assembly for a file
src/sokoban.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetHack_Companion.dir/build.make CMakeFiles/NetHack_Companion.dir/src/sokoban.cpp.s
.PHONY : src/sokoban.cpp.s

src/submenu.o: src/submenu.cpp.o
.PHONY : src/submenu.o

# target to build an object file
src/submenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetHack_Companion.dir/build.make CMakeFiles/NetHack_Companion.dir/src/submenu.cpp.o
.PHONY : src/submenu.cpp.o

src/submenu.i: src/submenu.cpp.i
.PHONY : src/submenu.i

# target to preprocess a source file
src/submenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetHack_Companion.dir/build.make CMakeFiles/NetHack_Companion.dir/src/submenu.cpp.i
.PHONY : src/submenu.cpp.i

src/submenu.s: src/submenu.cpp.s
.PHONY : src/submenu.s

# target to generate assembly for a file
src/submenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetHack_Companion.dir/build.make CMakeFiles/NetHack_Companion.dir/src/submenu.cpp.s
.PHONY : src/submenu.cpp.s

src/utilities.o: src/utilities.cpp.o
.PHONY : src/utilities.o

# target to build an object file
src/utilities.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetHack_Companion.dir/build.make CMakeFiles/NetHack_Companion.dir/src/utilities.cpp.o
.PHONY : src/utilities.cpp.o

src/utilities.i: src/utilities.cpp.i
.PHONY : src/utilities.i

# target to preprocess a source file
src/utilities.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetHack_Companion.dir/build.make CMakeFiles/NetHack_Companion.dir/src/utilities.cpp.i
.PHONY : src/utilities.cpp.i

src/utilities.s: src/utilities.cpp.s
.PHONY : src/utilities.s

# target to generate assembly for a file
src/utilities.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NetHack_Companion.dir/build.make CMakeFiles/NetHack_Companion.dir/src/utilities.cpp.s
.PHONY : src/utilities.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... NetHack_Companion"
	@echo "... src/gamemap.o"
	@echo "... src/gamemap.i"
	@echo "... src/gamemap.s"
	@echo "... src/input_handlers.o"
	@echo "... src/input_handlers.i"
	@echo "... src/input_handlers.s"
	@echo "... src/io.o"
	@echo "... src/io.i"
	@echo "... src/io.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/menu.o"
	@echo "... src/menu.i"
	@echo "... src/menu.s"
	@echo "... src/savefile.o"
	@echo "... src/savefile.i"
	@echo "... src/savefile.s"
	@echo "... src/sokoban.o"
	@echo "... src/sokoban.i"
	@echo "... src/sokoban.s"
	@echo "... src/submenu.o"
	@echo "... src/submenu.i"
	@echo "... src/submenu.s"
	@echo "... src/utilities.o"
	@echo "... src/utilities.i"
	@echo "... src/utilities.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

